name: health_data_store
description: A package to easily store health related data.
version: 1.0.2
publish_to: none

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  freezed_annotation: ^3.1.0
  json_annotation: ^4.9.0
  sqflite_common: ^2.5.5

dev_dependencies:
  build_runner: ^2.5.4
  coverage: ^1.15.0
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  mocktail: ^1.0.4
  sqflite_common_ffi: ^2.3.6
  test: ^1.26.2

