name: health_data_store
description: A package to easily store health related data.
version: 1.0.1+1
publish_to: none

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  sqflite_common: ^2.5.4+2

dev_dependencies:
  build_runner: ^2.4.12
  coverage: ^1.9.2
  freezed: ^2.5.7
  json_serializable: ^6.8.0
  mocktail: ^1.0.4
  sqflite_common_ffi: ^2.3.3
  test: ^1.25.8

