name: health_data_store
description: A package to easily store health related data.
version: 1.0.2
publish_to: none

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  freezed_annotation: ^3.0.0
  json_annotation: ^4.9.0
  sqflite_common: ^2.5.5

dev_dependencies:
  build_runner: ^2.4.15
  coverage: ^1.11.1
  freezed: ^3.0.4
  json_serializable: ^6.9.4
  mocktail: ^1.0.4
  sqflite_common_ffi: ^2.3.5
  test: ^1.25.15

