# This file configures the analyzer, which statically analyzes Dart code to
# check for errors, warnings, and lints.
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Error:
    - always_use_package_imports
    - avoid_slow_async_io
    - comment_references
    - no_wildcard_variable_uses
    - unawaited_futures

    # Style:
    - always_declare_return_types
    - avoid_annotating_with_dynamic
    - avoid_double_and_int_checks
    - avoid_escaping_inner_quotes
    - directives_ordering
    - eol_at_end_of_file
    - leading_newlines_in_multiline_strings
    - library_annotations
    - matching_super_parameters
    - no_literal_bool_comparisons
    - noop_primitive_operations
    - prefer_asserts_in_initializer_lists
    - prefer_expression_function_bodies
    - prefer_final_in_for_each
    - prefer_final_locals
    - prefer_if_elements_to_conditional_expressions
    - prefer_single_quotes
    - sort_constructors_first
    - type_annotate_public_apis
    - unnecessary_await_in_return
    - unnecessary_lambdas
    - unnecessary_null_aware_operator_on_extension_on_nullable
    - use_colored_box
    - use_decorated_box
    - use_if_null_to_convert_nulls_to_bools
    - use_to_and_as_if_applicable
    - void_checks

    # Pub
    - sort_pub_dependencies

analyzer:
  language:
    strict-inference: true
    strict-raw-types: true
    strict-casts: true
  exclude:
    # Testing takes enough time as is
    - test/**
    # TODO: clean up this code
    - lib/model/storage/**
