name: blood_pressure_app
description: Privacy focused, diary like app for storing blood pressure values.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.7.3+39
# F-Droid needs the Flutter version used to build releases to be in the repository.
# f-droid-flutter: 3.24.0-0.2.pre

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  csv: ^6.0.0
  collection: ^1.18.0
  intl: ^0.19.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.3
  fl_chart: ^0.68.0
  function_tree: ^0.9.1
  provider: ^6.1.2
  path: ^1.9.0
  pdf: ^3.11.0
  package_info_plus: ^8.0.1
  sqflite: ^2.3.3+1
  shared_preferences: ^2.3.0
  url_launcher: ^6.3.0
  health_data_store:
    path: ../health_data_store/
  flutter_bloc: ^8.1.6
  flutter_blue_plus: ^1.32.11

  # can become one custom dependency
  file_picker: ^8.0.6
  jsaver: ^1.3.0
  fluttertoast: ^8.2.6
  app_settings: ^5.1.1

  # desktop only
  sqflite_common_ffi: ^2.3.3

dev_dependencies:
  integration_test:
    sdk: flutter
  file: ^7.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  mockito: ^5.4.4
  translations_cleaner: ^0.0.5
  build_runner: ^2.4.12
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true
  generate: true

