name: blood_pressure_app
description: Privacy focused, diary like app for storing blood pressure values.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
repository: https://github.com/derdilla/blood-pressure-monitor-fl
issue_tracker: https://github.com/derdilla/blood-pressure-monitor-fl/issues

version: 1.8.2+44
# F-Droid needs the Flutter version used to build releases to be in the repository.
# f-droid-flutter: 3.24.4

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  csv: ^6.0.0
  collection: ^1.18.0
  intl: ^0.19.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.4+1
  function_tree: ^0.9.1
  provider: ^6.1.2
  path: ^1.9.0
  pdf: ^3.11.1
  package_info_plus: ^8.1.1
  week_of_year: 2.2.0
  sqflite: ^2.4.0
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.1
  health_data_store:
    path: ../health_data_store/
  flutter_bloc: ^8.1.6
  bluetooth_low_energy: ^6.0.2
  flutter_blue_plus: ^1.33.6
  archive: ^3.6.1
  file_picker: ^8.1.3
  fluttertoast: ^8.2.8
  app_settings: ^5.1.1
  logging: ^1.2.0
  persistent_user_dir_access_android: ^0.0.1

  # desktop only
  sqflite_common_ffi: ^2.3.4

dev_dependencies:
  integration_test:
    sdk: flutter
  file: ^7.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.4
  translations_cleaner: ^0.0.5
  build_runner: ^2.4.13
  bloc_test: ^9.1.7

flutter:
  uses-material-design: true
  generate: true
