name: blood_pressure_app
description: Privacy focused, diary like app for storing blood pressure values.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
repository: https://github.com/derdilla/blood-pressure-monitor-fl
issue_tracker: https://github.com/derdilla/blood-pressure-monitor-fl/issues

version: 1.8.10+52

environment:
  sdk: '>=3.0.2 <4.0.0'
  flutter: '3.35.7'

dependencies:
  collection: ^1.19.1
  csv: ^6.0.0
  intl: ^0.20.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.7+1
  function_tree: ^0.9.1
  provider: ^6.1.5+1
  path: ^1.9.1
  pdf: ^3.11.3
  package_info_plus: ^9.0.0
  week_of_year: 2.2.0
  sqflite: ^2.4.2
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.2
  health_data_store:
    path: ../health_data_store/
  flutter_bloc: ^9.1.1
  bluetooth_low_energy: ^6.1.0
  flutter_blue_plus: ^1.35.8
  archive: ^4.0.7
  file_picker: ^10.3.3
  app_settings: ^6.1.1
  logging: ^1.3.0
  persistent_user_dir_access_android: ^0.0.1
  share_plus: ^12.0.1

  # desktop only
  sqflite_common_ffi: ^2.3.6
  inline_tab_view: ^1.0.1
  xml: ^6.6.1

dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  file: ^7.0.1
  flutter_lints: ^6.0.0
  mockito: ^5.5.0
  translations_cleaner: ^0.0.5
  build_runner: ^2.7.1
  bloc_test: ^10.0.0

flutter:
  uses-material-design: true
  generate: true
