name: blood_pressure_app
description: Privacy focused, diary like app for storing blood pressure values.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
repository: https://github.com/derdilla/blood-pressure-monitor-fl
issue_tracker: https://github.com/derdilla/blood-pressure-monitor-fl/issues

version: 1.8.5+47
# F-Droid needs the Flutter version used to build releases to be in the repository.
# f-droid-flutter: 3.27.3

environment:
  sdk: '>=3.0.2 <4.0.0'
  flutter: '3.27.4'

dependencies:
  csv: ^6.0.0
  collection: ^1.19.0
  intl: ^0.19.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_markdown: ^0.7.6
  function_tree: ^0.9.1
  provider: ^6.1.2
  path: ^1.9.0
  pdf: ^3.11.2
  package_info_plus: ^8.1.4
  week_of_year: 2.2.0
  sqflite: ^2.4.1
  shared_preferences: ^2.5.1
  url_launcher: ^6.3.1
  health_data_store:
    path: ../health_data_store/
  flutter_bloc: ^9.0.0
  bluetooth_low_energy: ^6.0.2
  flutter_blue_plus: ^1.35.2
  archive: ^4.0.2
  file_picker: ^8.3.1
  fluttertoast: ^8.2.10
  app_settings: ^5.1.1
  logging: ^1.3.0
  persistent_user_dir_access_android: ^0.0.1

  # desktop only
  sqflite_common_ffi: ^2.3.4+4

dev_dependencies:
  integration_test:
    sdk: flutter
  file: ^7.0.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mockito: ^5.4.5
  translations_cleaner: ^0.0.5
  build_runner: ^2.4.14
  bloc_test: ^10.0.0

flutter:
  uses-material-design: true
  generate: true
