name: '📱 Application'

on:
  push:
    branches:
      - 'main'
    paths:
      - "app/**"
      - "health_data_store/**"
      - "settings_annotation/**"
      - "settings_builder/**"
      - "app-CI.yml"
  workflow_dispatch:

jobs:
  run-tests:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          sparse-checkout: |
            flutter/
            pubspec.yaml
            pubspec.lock
            app
            health_data_store
            settings_annotation
            settings_builder
      - run: git submodule update --init --recursive
      - run: echo "${{ github.workspace }}/flutter/bin" >> $GITHUB_PATH
      - name: Disable analytics
        run: flutter config --no-analytics --suppress-analytics
      - run: make get-deps
      - run: make codegen
      - run: make analyze
      - name: Run tests
        run: flutter test --no-pub
        working-directory: app
      - name: Run golden tests
        run: flutter test --no-pub --tags gold --run-skipped
        working-directory: app
