name: '📦 Packages'

on:
  push:
    branches:
      - 'main'
    paths:
      - "health_data_store/**"
      - ".github/workflows/pkg-CI.yml"
  workflow_dispatch:

jobs:
  test-health_data_store:
    name: '🧪 Test'
    runs-on: ubuntu-latest
 
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        # ensures there are no unexpected directories needed
        sparse-checkout: |
          health_data_store
    - name: Setup dart
      uses: dart-lang/setup-dart@v1
      with:
        sdk: stable
    - run: sudo apt-get -y install libsqlite3-dev

    - name: Get dependencies
      run: |
        dart pub get
        dart pub global activate coverage
      working-directory: ./health_data_store
    - name: Generate code
      run: dart run build_runner build
      working-directory: ./health_data_store
    - name: Analyze code
      run: dart analyze
      working-directory: ./health_data_store
    - name: Run tests
      run: |
        dart test --coverage=coverage
        format_coverage --lcov --in=coverage --out=coverage.lcov --report-on=lib
      working-directory: ./health_data_store
    - uses: actions/upload-artifact@v4
      with:
        name: health_data_store-coverage
        path: health_data_store/coverage.lcov
