name: '📦 Packages'

on:
  push:
    branches:
      - 'main'
    paths:
      - "health_data_store/**"
      - "settings_builder/**"
      - "settings_annotation/**"
      - ".github/workflows/pkg-CI.yml"
  workflow_dispatch:

jobs:
  changes:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: read
    outputs:
      settings_builder: ${{ steps.filter.outputs.settings_builder }}
      settings_annotation: ${{ steps.filter.outputs.settings_annotation }}
      health_data_store: ${{ steps.filter.outputs.health_data_store }}
    steps:
      - uses: actions/checkout@v6
        with:
          sparse-checkout: |
            health_data_store
            settings_annotation
            settings_builder
      - uses: dorny/paths-filter@v4
        id: filter
        with:
          filters: |
            settings_builder:
              - 'settings_builder/**'
            settings_annotation:
              - 'settings_annotation/**'
            health_data_store:
              - 'health_data_store/**'
  test-health_data_store:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.health_data_store == 'true' }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        sparse-checkout: |
          health_data_store
    - name: Setup dart
      uses: dart-lang/setup-dart@v1
      with:
        sdk: stable
    - run: sudo apt-get -y install libsqlite3-dev

    - name: Get dependencies
      run: |
        dart pub get
        dart pub global activate coverage
      working-directory: ./health_data_store
    - name: Generate code
      run: dart run build_runner build
      working-directory: ./health_data_store
    - name: Run tests
      run: |
        dart test --coverage=coverage
        format_coverage --lcov --in=coverage --out=coverage.lcov --report-on=lib
      working-directory: ./health_data_store
    - uses: actions/upload-artifact@v4
      with:
        name: health_data_store-coverage
        path: health_data_store/coverage.lcov
  test-settings_annotation:
    runs-on: ubuntu-slim
    needs: changes
    if: ${{ needs.changes.outputs.settings_annotation == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            settings_annotation
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          cache: true
      - name: Disable analytics
        run: flutter config --no-analytics --suppress-analytics
      - run: flutter test
        working-directory: ./settings_annotation
      - run: dart analyze
        working-directory: ./settings_annotation
      - name: Format
        run: dart format --output show --set-exit-if-changed .
        working-directory: ./settings_annotation
