name: 'PR checks'
on:
  pull_request:
    types:
      - synchronize
      - labeled
      - opened
      - reopened
    paths:
      - "app/**"
      - "health_data_store/**"
      - "settings_annotation/**"
      - "settings_builder/**"
      - ".github/workflows/pr.yml"
      - "pubspec.lock"

jobs:
  validate-localizations:
    runs-on: ubuntu-slim
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          sparse-checkout: "app/lib/l10n"
      - name: Check for [^'"]'[^'"] in .arb files as they will fail to parse
        run: "grep \"[^'\\\"]'[^'\\\"]\" app/lib/l10n/*.arb && exit 1 || exit 0"
  check-lints:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          sparse-checkout: |
            flutter/
            pubspec.yaml
            pubspec.lock
            app
            health_data_store
            settings_annotation
            settings_builder
      - run: git submodule update --init --recursive
      - run: echo "${{ github.workspace }}/flutter/bin" >> $GITHUB_PATH
      - name: Disable analytics
        run: flutter config --no-analytics --suppress-analytics
      - run: make get-deps
      - run: make codegen
      - name: Analyze code
        run: make analyze
  update-goldens:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Checkout PR code
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          sparse-checkout: |
            flutter/
            pubspec.yaml
            pubspec.lock
            app
            health_data_store
            settings_annotation
            settings_builder
      - run: git submodule update --init --recursive
      - run: echo "${{ github.workspace }}/flutter/bin" >> $GITHUB_PATH
      - name: Disable analytics
        run: flutter config --no-analytics --suppress-analytics
      - run: make get-deps
      - run: make codegen
      - name: Update goldens
        id: gold-upd
        run: flutter test --update-goldens --fail-fast --tags gold --run-skipped
        working-directory: app
      - name: Push golden changes
        # https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/evaluate-expressions-in-workflows-and-actions#example-of-failure-with-conditions
        if: ${{ steps.gold-upd.conclusion == 'success' }}
        run: |
          if [[ $(git status -s | grep png) ]]; then
              git config user.name "GitHub Action (update goldens)"
              git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
              git add app/test/
              git commit -m "Update goldens"
              git push origin HEAD:${{ github.event.pull_request.head.ref }}
          else
              echo "no changes to commit"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}%
  test:
    if: contains(github.event.pull_request.labels.*.name, 'auto-test')
    runs-on: ubuntu-latest
    needs: update-goldens # this is guaranteed to fail if goldens need to be updated
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          sparse-checkout: |
            flutter/
            pubspec.yaml
            pubspec.lock
            app
            health_data_store
            settings_annotation
            settings_builder
      - run: git submodule update --init --recursive
      - run: echo "${{ github.workspace }}/flutter/bin" >> $GITHUB_PATH
      - name: Disable analytics
        run: flutter config --no-analytics --suppress-analytics
      - run: make get-deps
      - run: make codegen
      - name: Run tests
        run: flutter test --coverage
        working-directory: app
  build:
    if: contains(github.event.pull_request.labels.*.name, 'auto-build')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          sparse-checkout: |
            flutter/
            pubspec.yaml
            pubspec.lock
            app
            health_data_store
            settings_annotation
            settings_builder
      - run: git submodule update --init --recursive
      - run: echo "${{ github.workspace }}/flutter/bin" >> $GITHUB_PATH
      - name: Disable analytics
        run: flutter config --no-analytics --suppress-analytics
      - run: make get-deps
      - run: make codegen
      - name: Set Up Java
        uses: actions/setup-java@v3.12.0
        with:
          distribution: 'oracle'
          java-version: '17'
      - name: Build
        run: |
          make prepare-build
          FLAVOR=fdroid make build-apk
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-results
          path: target
